apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: new-orders-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 4. New Orders
      name: new-orders-product
      description: >-
        Kafka Topics for new orders. 
      version: '1.0'
      categories:
          - Domain/Accounts
          - Protocol/Kafka
    gateways:
       - event-gateway
    plans:
      default-plan:
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: new-orders-api
  share:
    apim:
      providerOrg: providerorg
      catalog: sandbox
      credentialsSecret: apim-credentials
---
apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: new-orders-api
spec:
  definition:
    configMap: new-orders-api-cm
