apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: new-orders-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 4. New Orders
      name: new-orders-product
      description: >-
        Kafka Topics for new orders.  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
      version: '1.0'
      categories:
          - Domain/Accounts
          - Protocol/Kafka
    gateways:
       - event-gateway
    plans:
      default-plan:
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: new-orders-api
  share:
    apim:
      providerOrg: providerorg
      catalog: sandbox
      credentialsSecret: apim-credentials
---
apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: new-orders-api
spec:
  definition:
    configMap: new-orders-api-cm
